controller_list:
  - name: fake_placer_manipulator_controller
    joints:
      - placer_shoulder_pan_joint
      - placer_shoulder_lift_joint
      - placer_elbow_joint
      - placer_wrist_1_joint
      - placer_wrist_2_joint
      - placer_wrist_3_joint
  - name: fake_attacher_manipulator_controller
    joints:
      - attacher_shoulder_pan_joint
      - attacher_shoulder_lift_joint
      - attacher_elbow_joint
      - attacher_wrist_1_joint
      - attacher_wrist_2_joint
      - attacher_wrist_3_joint